### ISSUE TITLE
randomly summons 2 buttons

### ISSUE THREAD

**Issue by jary2003** [1ForeverHD/TopbarPlus#14]
help when i add the plugin to my new game without setting up buttons in my new game it makes 2 buttons what overide the hd admin button. How do i fix this?

https://user-images.githubusercontent.com/71220649/115546168-fc876500-a2a4-11eb-9a76-7956d59bc1b1.mp4

**Comment by 1ForeverHD** [comment]
Can you link us to an open source stripped down file of just the HD Admin and bugged icons please so we can take a look.

**Comment by jary2003** [comment]
> Can you link us to an open source stripped down file of just the HD Admin and bugged icons please so we can take a look.

I dont actualy know how to do that its my first game :) . 
I  Just took them from the roblox site. 
i Can upload a version of the game if that will help.

**Comment by 1ForeverHD** [comment]
You can uncopylock a place by ticking the following box:

![image](https://user-images.githubusercontent.com/51117782/115735745-a12ba480-a382-11eb-9582-501dfbf525f2.png)

![image](https://user-images.githubusercontent.com/51117782/115735759-a38dfe80-a382-11eb-8b78-436c7828a889.png)

Then simply provide a link to that place, e.g.
https://www.roblox.com/games/6339790000/Nanoblox-Development

**Comment by jary2003** [comment]
> You can uncopylock a place by ticking the following box:
> 
> ![image](https://user-images.githubusercontent.com/51117782/115735745-a12ba480-a382-11eb-9582-501dfbf525f2.png)
> 
> ![image](https://user-images.githubusercontent.com/51117782/115735759-a38dfe80-a382-11eb-8b78-436c7828a889.png)
> 
> Then simply provide a link to that place, e.g.
> https://www.roblox.com/games/6339790000/Nanoblox-Development

Its this https://www.roblox.com/games/6672427289/testgame1  but i dont think you can find something. 
BC its oke when i join it but in the editor it does strange. (and ye i alrdy did reinstal the editor)

**Comment by 1ForeverHD** [comment]
From what I can see this doesn't appear to be an issue with the TopbarPlus application itself.

I recommend seeking advice in Help and Feedback instead:
https://devforum.roblox.com/
