### ISSUE TITLE
Issues with Image Scale

### ISSUE THREAD

**Issue by the-trumpeter** [1ForeverHD/TopbarPlus#144]
I was introduced to TopBar Plus recently and am loving it, but I'm having issues with putting images in my widgets:

I uploaded an image to Roblox, and put it in my icon. It is exactly the same details as the system chat icon (size, resolution etc) but when used in TopBar Plus, it appears significantly smaller than the built in widgets:
(system, system, system, TopBar Plus, respectively)

<img width="251" alt="Screenshot 2024-12-01 at 9 45 44 am" src="https://github.com/user-attachments/assets/c9401b2b-58e6-4c4a-9f19-3cf6e7c1392b">

Here are the files I'm using:

My image, the one used in the TopBar Plus widget from screenshot:
![chatOff@3x copy](https://github.com/user-attachments/assets/e2c7db0c-3fc9-416f-93b9-576e3a7c917b)
Alternatively, on the [Creator Marketplace](https://drive.google.com/file/d/1EQzL_gy1b0lF2sGXyEoLFlc1QOE2U_XB/view?usp=sharing) (thats the EXACT ONE i used) or the original image on [Google Drive](https://drive.google.com/file/d/1EQzL_gy1b0lF2sGXyEoLFlc1QOE2U_XB/view?usp=sharing)

And the original chatOff@3x image (as shown on the system chat widget)
![chatOff@3x](https://github.com/user-attachments/assets/d86fa1d1-16d8-42b8-896f-43033f30fbf0)
Alternatively, [Google Drive](https://drive.google.com/file/d/1f0BtVbNMSxyQaf8GmPaVfpTOt-OdKPCf/view?usp=sharing) or find it yourself on your computer under _Roblox.app/Contents/Resources/content/textures/ui/TopBar/chatOff@3x.png_ (thats on MacOS, but Windows should be pretty similar)

And finally, my code: (This was copy/pasted from README, with a few changes. This is a brand new LocalScript in StarterCharachterScripts, with the 'Icon' modulescript in ReplicatedStorage. I have made no changes to the Icon bundle itself.

```
local reStore = game:GetService("ReplicatedStorage")
local Icon = require(reStore.Icon)


Icon.new()
	:setImage("http://www.roblox.com/asset/?id=137639351405756")
	:oneClick()
```

Can someone please tell me what is going on, and is it an issue with TopBar, or just me?
Also, sorry if Issues is a bad place to put this, I am unable to post on the DevForum yet otherwise I would have stuck it there!

Regards & apologies,
Gill

PS. My Roblox username is @stopthatchickenGP if that helps. It keeps putting a Mail link when I mention the chatOff image too, sorry

[Edit] My image is a little transparent too for some reason although I don't think thats whats causing it. The icon that I used here with TopBar Plus is actually 'shield.lefthalf.filled.badge.checkmark' from SF Symbols by Apple, which might be useful to you.

**Comment by Hunterk1241** [comment]
You can change the sizes of the icon images with `:setImageScale()` and `:setImageRatio()`!
