### ISSUE TITLE
localised text not displaying properly

### ISSUE THREAD

**Issue by RooflOmg** [1ForeverHD/TopbarPlus#38]
When the game is using localised text 
![image](https://user-images.githubusercontent.com/52837330/132850467-809e3524-948c-42cd-843d-9e00bc6073c5.png)
its not gonna display properly, when theres more width than the source one.
heres the preview of what will happen
![image](https://user-images.githubusercontent.com/52837330/132850791-ed595c11-f310-4f20-9919-ba5c893c3eae.png)

**Comment by 1ForeverHD** [comment]
Good idea, can you add the following code to your Icon module at line 755:
```lua
-- Localization support
instances.iconLabel:GetPropertyChangedSignal("Text"):Connect(function()
	local labelText = instances.iconLabel.Text
	local iconState = self:getIconState()
	local settingsText = self:get("iconText", iconState)
	if labelText ~= settingsText then
		self:setLabel(labelText)
	end
end)
```

If this works without causing any issues, can you then confirm please and I'll officially deploy an update for this. Thanks!

**Comment by RooflOmg** [comment]
> Good idea, can you add the following code to your Icon module at line 755:
> 
> ```lua
> -- Localization support
> instances.iconLabel:GetPropertyChangedSignal("Text"):Connect(function()
> 	local labelText = instances.iconLabel.Text
> 	local iconState = self:getIconState()
> 	local settingsText = self:get("iconText", iconState)
> 	if labelText ~= settingsText then
> 		self:setLabel(labelText)
> 	end
> end)
> ```
> 
> ![image](https://user-images.githubusercontent.com/51117782/132866206-11d37143-653a-4d0c-957d-1ec07a940587.png)
> 
> If this works without causing any issues, can you then confirm please and I'll officially deploy an update for this. Thanks!

![image](https://user-images.githubusercontent.com/52837330/132955834-0094c0ed-cda6-4f37-9615-d312a61c3bec.png)
still doesnt work

**Comment by 1ForeverHD** [comment]
Okay thanks for the report, it appears the labels aren't detecting as changed with localized text (therefore not expanding). I will provide a fix for this and complete support for localization in the next update (although I can't guarantee when as Nanoblox is currently our top priority).

**Comment by 1ForeverHD** [comment]
Resolved in [v.2.8.0](https://github.com/1ForeverHD/TopbarPlus/releases/tag/v2.8.0)!
