### ISSUE TITLE
Signal doesn't support yielding connections

### ISSUE THREAD

**Issue by LucasMZReal** [1ForeverHD/TopbarPlus#40]
A yielding connection will cause the next connection to run only after the current connection has stopped yielding.
This is unexpected behaviour, especially since I believe this library used a bindable event implementation a while ago, on which this wasn't an issue.

I've encountered this as an issue a while ago since I was messing with tweening menus and I was using `Tween.Completed:Wait` and I guess you could know what happened.

**Comment by 1ForeverHD** [comment]
You're absolutely correct, this was fixed a few months ago for ZonePlus although it looks like we haven't made the same transition for this to GoodSignal. This will be fixed for the next release of TopbarPlus although I can't guarantee any times yet.

Thanks for the ticket, I'll close it once the new release it out.
