### ISSUE TITLE
Inconsistency in variable names [DOCUMENTS]

### ISSUE THREAD

**Issue by cens6r** [1ForeverHD/TopbarPlus#44]
In the introduction section, the docs uses the variable name "Icon" to require the module.
```lua
local Icon = require(game:GetService("ReplicatedStorage").Icon)
```

However, in the features section, the docs uses the variable name "iconModule" to require the module.
```lua
local iconModule = game:GetService("ReplicatedStorage").Icon
```

I believe small inconsistencies like this are critical in documents that a large number of users view and I think it would be easier for everyone for this issue to be fixed!

Thanks for the awesome module btw

**Comment by 1ForeverHD** [comment]
This is intentional: ``iconModule`` is referencing a module instance, while ``Icon`` is referencing the return value of that module after being required. I think you might be confusing them as the same thing.
