### ISSUE TITLE
Words are Cut off the Icons

### ISSUE THREAD

**Issue by ValiantWind** [1ForeverHD/TopbarPlus#54]
@Not0ffSale on Roblox found a bug where if you disabled and re-enabled the CoreGui, existing TopBarPlus icons would have some of their words cut off, as shown below:

![image](https://user-images.githubusercontent.com/83314733/182944116-5e50cbe3-9515-408c-99af-3f80db5dfe3a.jpeg)

**Comment by ValiantWind** [comment]
Any updates on this @1ForeverHD ?

**Comment by 1ForeverHD** [comment]
Resolved in [v.2.8.0](https://github.com/1ForeverHD/TopbarPlus/releases/tag/v2.8.0)!

**Comment by ValiantWind** [comment]
Great! Thanks :D
