### ISSUE TITLE
Font Clipping Issue Type:Bug

### ISSUE THREAD

**Issue by Inctus** [1ForeverHD/TopbarPlus#60]
## Reproduction Code and Place Link

*Reproduction Place Link: https://www.roblox.com/games/10845284955/TopbarPlus-Text-Clipping-Repro*

```lua
Icon.new()
	:setLabel("Hello World")
	:set("iconFont", Enum.Font.Arcade)
```

## Description of Issue | Proposed General Fix

The issue occurs as a result of the TextBounds not being recalculated for each font change.

**Comment by 1ForeverHD** [comment]
Thanks for the report! This is likely also related to: https://github.com/1ForeverHD/TopbarPlus/issues/38#issuecomment-1003734899

We can use the recently released Font APIs to overcome these more effectively:
https://devforum.roblox.com/t/new-font-ui-beta/1967004

**Comment by 1ForeverHD** [comment]
Exploring further here:
https://devforum.roblox.com/t/how-to-remove-all-richtext-tags-from-text-without-using-textcontenttext-or-how-to-get-size-of-text-while-ignoring-richtext-tags/1994576

**Comment by 1ForeverHD** [comment]
Resolved in [v.2.8.0](https://github.com/1ForeverHD/TopbarPlus/releases/tag/v2.8.0)!
