### ISSUE TITLE
UI not showing then interacted

### ISSUE THREAD

**Issue by DionBlox1** [1ForeverHD/TopbarPlus#64]
Hello. I was working on a Ui game but the ui won't open.

https://user-images.githubusercontent.com/90649001/192615420-d9ce94bf-e649-4bcc-b5bc-da44dfd6663b.mp4

Script:
--Getting the module to work the script
local Icon = require(game:GetService("ReplicatedStorage").Icon)
local IconController = require(game:GetService("ReplicatedStorage").Icon.IconController)
local Themes = require(game:GetService("ReplicatedStorage").Icon.Themes)
IconController.setGameTheme(Themes["BlueGradient"])

--All icons
local Emails = Icon.new()

 --Get UI
local EmailsGUI = game.StarterGui.Emails.Mainbase

Emails:setImage(11084222714)
Emails:setLabel("Email", "deselected")
Emails:setLabel("You have "..game.StarterGui.Emails.Numofemails.Value.." new messages", "hovering")
Emails:setLabel("Email", "selected")
Emails:bindEvent("selected", function()
	print("selected!")
	EmailsGUI.Visible = true
end)
Emails:bindEvent("deselected", function()
	print("deselected!")
	EmailsGUI.Visible = false
end)

Game: https://drive.google.com/file/d/1pP1LAJ9dJt4X165-JonUeNDBxgRp8X_w/view?usp=sharing

**Comment by 1ForeverHD** [comment]
For help support can you ask your question on the devforum discussion post please as I have to prioritize the most important bugs: https://devforum.roblox.com/t/topbarplus-v277-construct-intuitive-topbar-icons-customise-them-with-themes-dropdowns-captions-labels-and-much-more/1017485

**Comment by DionBlox1** [comment]
It wornt let me talk in dev fourm even though I'm a member
![Screenshot_20220928_122423](https://user-images.githubusercontent.com/90649001/192767412-2436d7c0-9da8-49f0-9196-3f5c20233582.jpg)
![Screenshot_20220928-122611_Samsung Internet](https://user-images.githubusercontent.com/90649001/192767423-729bcf4e-a00b-4a5d-9a8d-2400f9c42380.jpg)

**Comment by 1ForeverHD** [comment]
Your code looks fine from what I can see at a glance. I recommend posting a help thread in scripting support once your permissions appear

**Comment by DionBlox1** [comment]
My devfourm acount is on hold for 2 years

**Comment by DionBlox1** [comment]
Hello?
