### ISSUE TITLE
Where to report HD Admin issues?

### ISSUE THREAD

**Issue by karl-police** [1ForeverHD/TopbarPlus#69]
I don't use HD Admin but there's games that do use it so what I am wondering is where to report issues.

**Comment by ValiantWind** [comment]
Try asking on the Roblox Developer Forum

https://devforum.roblox.com

**Comment by karl-police** [comment]
> Try asking on the Roblox Developer Forum
> 
> https://devforum.roblox.com

do they put bug reports on a thread called HD Admin bug reports or?

**Comment by ValiantWind** [comment]
There is no thread for HD Admin, no. However, there are several people on the DevForum willing to help you resolve your issue.

Try posting your issue in #help-and-feedback:scripting-support stating the details of the problem.
