### ISSUE TITLE
Support new roblox topbar

### ISSUE THREAD

**Issue by christopher-buss** [1ForeverHD/TopbarPlus#77]
https://devforum.roblox.com/t/studio-beta-for-experience-controls-available-now/2567355

The new studio experience controls means the topbar themeing and sizes no longer match the incoming changes.

**Comment by fgclue** [comment]
I'm having this problem, it just got rolled out to me.

**Comment by iamEvanYT** [comment]
https://github.com/1ForeverHD/TopbarPlus/pull/82
