### ISSUE TITLE
Version 2.4.1

### ISSUE THREAD

**Issue by 1ForeverHD** [1ForeverHD/TopbarPlus#8]
### Hover and expand text
- [x] If setLabel longtext then wait and setlabel shortertext the icon size does not adapt
- [x] Description:- does not expand (when resizing)
- [x] change 'unqiue' to 'group'
- [x] update the following features so they're all in a central place:
  - [x] caption - added displayCaption and captionVisible
  - [x] tips - added displayTip and tipVisible
- [x] items like hints and captions do not hide when clicked
- [x] overflows slightly bug after icons leave dropdown when re-expanding
- [x] introduce a position action tween too
- [x] renamed ``resizeTransitionInfo`` to ``resizeInfo``
- [x] added ``repositionInfo``
- [x] update Default.lua
- [x] updated BlueGradient theme
- [x] instead of a method like setAutoScaling() to wrap it all together, utilise state below
- [x] update the playground with this neater method
- [x] test alongside overflows
- [x] add Icon:give(RBXScriptSignal) - gives the function to the icons maid

### icon-state (formerly toggleable)
- [x] consider renaming 'toggleable' and 'toggleState' to simply 'iconState'
- [x] introduce 'hovering' icon state
- [x] this appears to glitch when joining/leaving dropdowns, menus and console mode
- [x] the toggleable/state tags appear to have disappeared?
- [x] add a table to the API which shows state values
- [x] ensure these state values work together (e.g. hoverStarted and selected)
- [x] test the following ``:setLabel("Nanoblox", "hoverStarted")`` vs ``:setLabel("Nanoblox", "selected") :setLabel("Nanoblox", "hoverStarted")``

### Additional
- [x] autowrite version to top of module or a separate module as a comment, maybe https://github.com/marketplace/actions/write-version-to-file?
- [x] Add IconController.updateTopbar to API
- [x] Remove ``local runservice`` from Third Parties page code example
- [x] When countdown ends, the overflows sometimes dont refresh back to normal (test mobile)
- [x] Inaccurate notice amounts (test on mobile)
- [x] Update HD Admin with new version of TopbarPlus

**Comment by supeman334** [comment]
Give me all them
