### ISSUE TITLE
Gfycat no longer exists, so videos on the documentation website are broken.

### ISSUE THREAD

**Issue by fgclue** [1ForeverHD/TopbarPlus#80]
Since Gfycat shut down on September 1st, the videos on the website no longer work.
Since it cannot find the video, firefox just shows this error.
![I'm SOOOOOOOOOOOOOOOOOOOOOO SORRY WE CANT FIND THE VIDEO :((](https://github.com/1ForeverHD/TopbarPlus/assets/87581499/b8b4a38b-3674-43d2-91e4-b1e64c6b24c1)

And, when you try to go to the source URL, it doesn't work.
![U'mmmmm, we'reeeeeeeeee HAVING TROUBLE!!!! SHOWING YOU THIS BECAUSE someoneeeeeee PULLED THE SERVER WIRES!!!!!!!!!!!!"> <img src="" onclick="alert(1)"> "](https://github.com/1ForeverHD/TopbarPlus/assets/87581499/b484bf3e-ad47-4221-b43f-04065fca874f)

**Comment by 1ForeverHD** [comment]
Will upload some new videos shortly, thanks

**Comment by 1ForeverHD** [comment]
Resolved in v3.0.0
