### ISSUE TITLE
WaitForChild(ChatMain) warning appears due ChatMain no longer being added to the player for new games (with the new chat)

### ISSUE THREAD

**Issue by 1ForeverHD** [1ForeverHD/TopbarPlus#9]
- [ ] see if the chatmain script can still be referenced
- [ ] fix the warning
- [ ] update nanoblox tag
- [ ] update hd admin with new topbarplus version

**Comment by MirayXS** [comment]
hello @1ForeverHD 

Is this issue the reason my first icon, which is located at the left, get's glitched like this?
> ![image](https://user-images.githubusercontent.com/55494819/111040488-6b1a0d00-8433-11eb-8227-b28e66c1b990.png)

Sometimes it works well, but most of the time it just glitches.
Sometimes it doesn't even show the icon at all but its only clickable/toggleable like this

> ![image](https://user-images.githubusercontent.com/55494819/111040397-16769200-8433-11eb-9d34-d929dc57b91c.png)

**Comment by MirayXS** [comment]
> hello @1ForeverHD
> 
> Is this issue the reason my first icon, which is located at the left, get's glitched like this?
> 
> > ![image](https://user-images.githubusercontent.com/55494819/111040488-6b1a0d00-8433-11eb-8227-b28e66c1b990.png)
> 
> Sometimes it works well, but most of the time it just glitches.
> Sometimes it doesn't even show the icon at all but its only clickable/toggleable like this
> 
> > ![image](https://user-images.githubusercontent.com/55494819/111040397-16769200-8433-11eb-9d34-d929dc57b91c.png)
```lua
-- PLayer Guis
local gui = playerGui:WaitForChild("PhysicsSettings")


-- Leftwards icons

local settingsMenu = gui
local settingsIcon = Icon.new()
:setImage(2484556379)
:setLabel("Settings")
:setTip("Open Settings (b)")
:setCaption("Physics Settings")
:bindToggleKey(Enum.KeyCode.B)

:setOrder(1)

:setLeft()

--:notify()
:bindEvent("selected", function()
	print("selected!")
	settingsMenu.Enabled = true
end)
:bindEvent("deselected", function()
	print("deselected!")
	settingsMenu.Enabled = false
end)
```

**Comment by 1ForeverHD** [comment]
Can you open a separate issue for this please and Ill take a look tomorrow or Monday

**Comment by MirayXS** [comment]
> Can you open a separate issue for this please and Ill take a look tomorrow or Monday

Alright, i will make a issue later or right now
