### ISSUE TITLE
Older-style topbar icons are slightly vertically misaligned

### ISSUE THREAD

**Issue by qfoxb** [1ForeverHD/TopbarPlus#97]
![image](https://github.com/1ForeverHD/TopbarPlus/assets/42038239/b7c15af6-8a08-45e5-b6f2-797062110f02)
In this image - you can see the CoreGui icons touching the top of my GUI while the TopbarPlus ones are slightly floating above it

**Comment by 1ForeverHD** [comment]
Thanks for the report, will be shifting the classic theme down by a pixel (or two) for the next patch 👍

**Comment by 1ForeverHD** [comment]
Resolved in v3.0.1
